"""add phone and weixin

Revision ID: 37ea3953ba03
Revises: e78938f836f3
Create Date: 2020-04-22 11:07:01.822107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37ea3953ba03'
down_revision = 'e78938f836f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('phone', sa.String(length=11), nullable=True))
    op.add_column('admin', sa.Column('weixin', sa.String(length=60), nullable=True))
    op.drop_column('admin', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('name', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('admin', 'weixin')
    op.drop_column('admin', 'phone')
    # ### end Alembic commands ###
